version: '3'  # version of the docker-compose file format (DO NOT CHANGE)

networks:
  # User-defined bridges provide automatic DNS resolution between containers
  eggnet:  # the name of my user-defined network
    external: false

services:
  bot:
    container_name: bot
    build: ./Eggbort  # use build if there is a Dockerfile in that directory
    volumes:
      - ./Eggbort:/usr/src/app
    environment:
      - EGGBORT_TOKEN=${EGGBORT_TOKEN}  # gets environment var from shell
    networks:
      - eggnet
    depends_on:
      - lavalink

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - eggnet