version: '3'  # version of the docker-compose file format (DO NOT CHANGE)

# User-defined bridges provide automatic DNS resolution between containers
networks:
  eggnet:  # the name of my user-defined network
    external: true  # network was created outside of this file

services:
  bot:
    container_name: bot
    build: ./Eggbort  # use build if there is a Dockerfile in that directory
    volumes:
      - ./Eggbort:/usr/src/app
    environment:
      - EGGBORT_TOKEN=${EGGBORT_TOKEN}  # gets environment var from shell
    networks:
      - eggnet
    depends_on:
      - db
      - lavalink
    restart: always

  db:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: poggo_db
    networks:
      - eggnet
    restart: always

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    networks:
      - eggnet
    restart: always